[package]
name = "testserver"
version = "0.1.0"
authors = ["Uwe <uriegel@hotmail.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.5.0", features = ["full"] }
warp = "0.3"
chrono = "0.4"